### ISSUE TITLE
Out of map range behaviour ?

### ISSUE THREAD

**Issue by GitNitneroc** [Luka967/SpatialHash#1]
Hi, and thanks for the amazing work on this module !

I'm currently debugging a nasty problem in my project, and my last idea before going to bed is that your SpatialHash might have strange behaviour if a query range goes out of map dimensions. 
Whether it's the case or not, maybe this should be specified in Readme (or maybe I'm the only one wondering this).
Thank you !

**Comment by Luka967** [comment]
It should throw an exception as soon as a non-existing bucket gets called, i.e. it must be inside the hash's boundaries.
You can mitigate this by increasing the hash's width & height by an approximation of the objects' maximum width & height respectively.
I'll specify this in the readme now, thanks for reporting 👍

**Comment by GitNitneroc** [comment]
thanks for your quick answer.

Now that you mention increasing hash's dimensions, am I correct assuming
negative values are supported ? Thanks again

2017-02-27 0:08 GMT+01:00 Luka <notifications@github.com>:

**Comment by Luka967** [comment]
Negative values are supported, don't worry.

**Comment by GitNitneroc** [comment]
Thanks again

**Comment by GitNitneroc** [comment]
Excuse me for being stupid, I'm sure I'm overlooking something easy, but I don't understand this behaviour 
```
 'use strict';

const SpatialHash = require('spatialhash-2d');
var occupants = new SpatialHash({x:0,y:0,w:51,h:54}, 6);

var testItem = {range:{x: 3, y : 3, w:0,h:0}};
occupants.insert(testItem);

var w = occupants.query({x:5,y:6,w:20,h:12});
for (let i = 0; i <w.length; i++){
    console.log (w[i]);
}
```

testItem being at x=3 y=3, it shouldn't be found in my query. yet the output is 
`{ range: { x: 3, y: 3, w: 0, h: 0 },
  __b: { hStart: 0, hEnd: 0, vStart: 0, vEnd: 0, id: -9000000000000000 } }`

Sorry for bothering you...

**Comment by GitNitneroc** [comment]
OK, I found how stupid how I am... I just read your readme again, and found that x and y are center and w and h are half-length...
Sorry !
